version: '3.8'

services:
  app:
    build: .
    container_name: crm-inmobiliario-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=OHdlwmnrEjkwfvlWjdxPEYflpqxlGFb
    networks:
      - crm-network
    command: ["java", "-jar", "app.jar"]

networks:
  crm-network:
    driver: bridge
