package com.backend.crmInmobiliario.DTO.IA;

public enum IntentType {
    CONTAR_GARANTES,
    LISTAR_GARANTES,

    CONTAR_PROPIETARIOS,
    LISTAR_PROPIETARIOS,

    CONTAR_INQUILINOS,
    LISTAR_INQUILINOS,

    CONTAR_PROPIEDADES,
    LISTAR_PROPIEDADES,

    CONTAR_CONTRATOS,
    LISTAR_CONTRATOS,
    ANALISIS_CONTRATOS_COMPLETO,

    CONTRATOS_POR_PERSONA,
    CONTRATOS_POR_VENCIMIENTO,

    SALDO_PENDIENTE_RECIBOS,
    CONSULTA_GENERAL,
    GANANCIA_MES_ACTUAL,
    GANANCIA_MES_ESPECIFICO,
    DISTRIBUCION_INGRESOS_ANUAL,
    TOP_CONTRATOS_INGRESOS,
    DATOS_CONTACTO_PERSONA,
    CONTRATOS_ACTUALIZAN_MES,
    FECHA_ACTUALIZACION_CONTRATO,
    CONTRATOS_VENCEN_MES
}
