spring.application.name=crmInmobiliario
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%highlight(%-5level)] [%cyan(%thread)] %magenta(%logger{15}) - %msg%n
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
logging.level.org.hibernate.engine.internal=TRACE
logging.level.org.springframework.transaction=TRACE
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:42853/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=JCTuzDYhuwhThNdwhVNLVxKFXseCaMss
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
security.jwt.expiration-minutes=1000
security.jwt.key.private=daa34b8c7d5b78820ddbc1ac250962f7b758c15b12aa4e0039c9a33aede8f47a
security.jwt.user.generator=AUTH0JWT-BACKEND
security.jwt.access.minutes=15
security.jwt.refresh.days=30
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.FAIL_ON_SELF_REFERENCES=true
spring.jackson.serialization.FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS=true
openai.apikey=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
openai.embedding.url=https://api.openai.com/v1/embeddings
openai.embedding.model=text-embedding-3-small
openai.chat.url=https://api.openai.com/v1/chat/completions
openai.chat.model=gpt-4o
qdrant.host=http://qdrant:6333
qdrant.collection=documentos
qdrant.vector.size=1536
supabase.url=https://kksdxwqcgrbemlpgjifr.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2R4d3FjZ3JiZW1scGdqaWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzM4NDEsImV4cCI6MjA2MDQwOTg0MX0.1VxlR2YSdnwvVkAZ0df8eZo3PBiMr90sbr9PgTQhQ-U
supabase.service.role.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2R4d3FjZ3JiZW1scGdqaWZyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDgzMzg0MSwiZXhwIjoyMDYwNDA5ODQxfQ.q7x_ryNbtH_afCmsIeRbguREll0aeiJdUZh15vdZyas
n8n.webhook.url=https://primary-production-9170b.up.railway.app/webhook/31431941-8c7f-4e58-a45f-6de60de45825/chat

google.client.id=200672878714-4a696o4p969fvu2o7hq031chbi02n6f9.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=https://crminmobiliario-app-production.up.railway.app/rest/oauth2-credential/callback
app.crypto.secret=/JjeJef2CqZRy0igNH/qkZZ0rR5veozcRltxy6BrFqc=
#spring.security.oauth2.client.registration.google.client-id=200672878714-4a696o4p969fvu2o7hq031chbi02n6f9.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/documents,https://www.googleapis.com/auth/drive.file
#spring.security.oauth2.client.registration.google.client-name=google
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub





server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

# Límite de contratos para usuarios sin plan (trial)
app.contracts.trial-limit=3


# Clave secreta de Stripe
#stripe.secret-key=sk_test_XXXXXXXXXXXXXXXXXXXXXXXX

# URL de redirección después del pago
#stripe.success-url=http://localhost:3000/success
#stripe.cancel-url=http://localhost:3000/cancel

# IDs de precios de tus planes (los que configurás en Stripe Dashboard)
#stripe.price.free=price_123FREE
#stripe.price.starter=price_123STARTER
#stripe.price.pro=price_123PRO

#payment.provider=dummy

#payment.provider=stripe
#stripe.secret-key=sk_test_51S6wRa2MyxXOhzhFSSHHyrrCEwQFuJBhXP0f24FHo8wlEcBtdgJXT2X5pRjqu2cXYnFNnSg5UBm5l4CEvVj4cZfg00mIli28RZ
#stripe.webhook-secret=whsec_Ld5ALNNfE15mx3Ds1hHYmgKGAiVa5Gvl
#stripe.success-url=http://localhost:3000/billing/success?session_id={CHECKOUT_SESSION_ID}
#stripe.cancel-url=http://localhost:3000/billing/cancel
#
## Price IDs reales creados en Stripe Dashboard
#stripe.priceIds={FREE:'price_1SBgh62MyxXOhzhFXeCDjX3f',PROFESIONAL:'price_1SBfxk2MyxXOhzhF8mlredyC',SUPERIOR:'price_1SBg3V2MyxXOhzhFTdHKXDMO'}


payment.provider=mercadopago
mp.access.token:=APP_USR-5046281913019324-092713-840cbca15befb8043072e120e527ae92-157704548
mp.success-url=https://tuinmo.net/pay/success
mp.pending-url=http://localhost:3000/billing/pending
mp.failure-url=http://localhost:3000/billing/failure
mp.service.url=https://mpserviceapp-production.up.railway.app
mp.notification.url=https://crminmobiliario-app-production.up.railway.app/api/webhooks/mercadopago

# Si implementás preapproval y tenés IDs de plan, opcional:
#mp.planIds={PROFESIONAL:'18d6bbb4e52647c493b28ff55b0431e2',SUPERIOR:'cf45805a45e9499cb7e8bb2e8b351f5d'}
mp.planIds={"PLAN-PRO":"098541d27f174cd6a93a8e688058b1db","PLAN-PROF":"441f2b774dba4843bd17ff01dbfbd8ca","PLAN-SUP":"f467ee5475bb4541bbee70fb2b3b407f"}

#PLAN_MAP={"PROFESIONAL":"18d6bbb4e52647c493b28ff55b0431e2", "SUPERIOR":"cf45805a45e9499cb7e8bb2e8b351f5d }
PLAN_MAP={"PLAN-PRO":"098541d27f174cd6a93a8e688058b1db","PLAN-PROF":"441f2b774dba4843bd17ff01dbfbd8ca","PLAN-SUP":"f467ee5475bb4541bbee70fb2b3b407f"}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bewebworld@gmail.com
spring.mail.password=cnfowwfentdzjtoz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


vapid.public=BGzu5wLGTcrHWXRT34ikcqPN3g2z8eyn7edKci4FjGbUoTU9CWntZE2V8QInx2uB5Xa82Zn8TMuOvfVzBMauwJ8
vapid.private=yM_r4gCzfCTpzZr8_NH4XaOblzNr_ON12MbgaohoZjM
vapid.subject=bewebworld@gmail.com
