package com.backend.crmInmobiliario.entity.oficios;

import java.util.List;

public record CategoriaOficio(String grupo, String nombre) {

    public static List<CategoriaOficio> catalogoBase() {
        return List.of(
                new CategoriaOficio("Mantenimiento y Reparaciones", "Electricista matriculado"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Plomero / Gasista"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Gasista matriculado"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Cerrajero"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Carpintero"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Pintor"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Albañil"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Yesero"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Techista"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Impermeabilización de terrazas"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Durlock / construcción en seco"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Instalador de calefones y termotanques"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de estufas"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Service de aire acondicionado"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Instalador de aire acondicionado"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de persianas"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de cortinas de enrollar"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Vidriero"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de puertas y ventanas"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de portones eléctricos"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de ascensores"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Electricidad en consorcios"),
                new CategoriaOficio("Mantenimiento y Reparaciones", "Reparación de bombas de agua"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Servicio de limpieza profunda"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Limpieza post obra"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Servicio de desinfección"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Control de plagas"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Parquetero / pulido y plastificado"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Pulido de mármol"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Colocador de pisos flotantes"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Colocador de cerámicos"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Instalador de mamparas"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Instalador de artefactos sanitarios"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Instalador de iluminación LED"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Armador de muebles"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Mudanzas"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Mini fletes"),
                new CategoriaOficio("Preparación de la propiedad para alquilar", "Servicio de retiro de escombros"),
                new CategoriaOficio("Comercialización", "Fotógrafo inmobiliario"),
                new CategoriaOficio("Comercialización", "Videógrafo"),
                new CategoriaOficio("Comercialización", "Tour virtual 360°"),
                new CategoriaOficio("Comercialización", "Drone"),
                new CategoriaOficio("Comercialización", "Home staging"),
                new CategoriaOficio("Comercialización", "Diseñador de planos 3D"),
                new CategoriaOficio("Comercialización", "Diseñador gráfico (cartelería)"),
                new CategoriaOficio("Comercialización", "Impresión de carteles"),
                new CategoriaOficio("Comercialización", "Instalación de carteles en obra"),
                new CategoriaOficio("Servicios técnicos y legales", "Escribano"),
                new CategoriaOficio("Servicios técnicos y legales", "Gestor"),
                new CategoriaOficio("Servicios técnicos y legales", "Abogado inmobiliario"),
                new CategoriaOficio("Servicios técnicos y legales", "Martillero público"),
                new CategoriaOficio("Servicios técnicos y legales", "Tasador"),
                new CategoriaOficio("Servicios técnicos y legales", "Agrimensor"),
                new CategoriaOficio("Servicios técnicos y legales", "Arquitecto"),
                new CategoriaOficio("Servicios técnicos y legales", "Maestro mayor de obras"),
                new CategoriaOficio("Servicios técnicos y legales", "Ingeniero civil"),
                new CategoriaOficio("Servicios técnicos y legales", "Ingeniero eléctrico"),
                new CategoriaOficio("Servicios técnicos y legales", "Certificado de gas"),
                new CategoriaOficio("Servicios técnicos y legales", "Certificado eléctrico"),
                new CategoriaOficio("Servicios técnicos y legales", "Certificado de habitabilidad"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Administrador de consorcio"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Limpieza de consorcios"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Mantenimiento de ascensores"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Seguridad privada"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Portería"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Cámaras de seguridad"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Instalador de alarmas"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Control de acceso"),
                new CategoriaOficio("Servicios para edificios y consorcios", "Servicio de matafuegos"),
                new CategoriaOficio("Exteriores", "Jardinero"),
                new CategoriaOficio("Exteriores", "Poda en altura"),
                new CategoriaOficio("Exteriores", "Parquización"),
                new CategoriaOficio("Exteriores", "Instalación de riego automático"),
                new CategoriaOficio("Exteriores", "Limpieza de piletas"),
                new CategoriaOficio("Exteriores", "Mantenimiento de piletas"),
                new CategoriaOficio("Exteriores", "Reparación de cercos")
        );
    }
}
